# Generated by Django 6.0.5 on 2026-05-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('Estudantil', 'estudantil'), ('Sind', 'sindical'), ('Associacao', 'associacao'), ('Condominio', 'condominio'), ('Conselho', 'conselho'), ('Outra', 'outra')], max_length=20)),
                ('status', models.CharField(choices=[('Rascunho', 'rascunho'), ('Aberta', 'aberta'), ('Encerrada', 'encerrada'), ('Apurada', 'apurada')], default='rascunho', max_length=20)),
                ('permite_branco', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=150)),
                ('nome_urna', models.CharField(max_length=50)),
                ('partido_ou_chapa', models.CharField(blank=True, max_length=150)),
                ('proposta', models.TextField(blank=True)),
                ('foto_url', models.URLField(blank=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='urna.eleicao')),
            ],
            options={
                'unique_together': {('eleicao', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='eleicao',
            name='criada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eleicoes_criadas', to='urna.eleitor'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_branco', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('comprovante_hashCharField', models.CharField(max_length=64, unique=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.candidato')),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='urna.eleicao')),
            ],
        ),
        migrations.CreateModel(
            name='AptidaoEleitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptos', to='urna.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aptidoes', to='urna.eleitor')),
            ],
            options={
                'unique_together': {('eleitor', 'eleicao')},
            },
        ),
        migrations.CreateModel(
            name='RegistroVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('eleicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_votacao', to='urna.eleicao')),
                ('eleitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_votacao', to='urna.eleitor')),
            ],
            options={
                'unique_together': {('eleitor', 'eleicao')},
            },
        ),
    ]
